service: test-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2

functions:
  hello:
    handler: handler.hello
    timeout: 60
    events:
      - httpApi:
          path: /
          method: '*'
